name: MINI-AC test suite

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Nextflow
      uses: nf-core/setup-nextflow@v1.3.0

    - name: Setup singularity
      uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3

    - name: Setup nf-test
      run: wget -qO- https://code.askimed.com/install/nf-test | bash

    - name: Fetch motif mapping files
      run: |
        curl -k -o tests/data/zma_v4/zma_v4_genome_wide_motif_mappings_chr1.bed https://floppy.psb.ugent.be/index.php/s/NekMYztyxEnsQiY/download/zma_v4_genome_wide_motif_mappings_chr1.bed
        curl -k -o tests/data/zma_v4/zma_v4_locus_based_motif_mappings_5kbup_1kbdown_chr1.bed https://floppy.psb.ugent.be/index.php/s/r2wQmFjPy79qSp7/download/zma_v4_locus_based_motif_mappings_5kbup_1kbdown_chr1.bed
        curl -k -o tests/data/ath/ath_genome_wide_motif_mappings.bed https://zenodo.org/record/7974527/files/ath_genome_wide_motif_mappings.bed?download=1
        curl -k -o tests/data/ath/ath_locus_based_motif_mappings_5kbup_1kbdown.bed https://zenodo.org/record/7974527/files/ath_locus_based_motif_mappings_5kbup_1kbdown.bed?download=1

    - name: Prepare nf-test config file
      run: mv .github/workflows/test.yml tests/nextflow.config

    - name: Run nf-test
      run: ./nf-test test
